config/routes.rb
Rails.application.routes.draw do
  resources :saches
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "saches#index"
  get "/articles", to: "articles#index"
  get "/saches", to: "saches#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sach.rb
class Sach < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end
end

app/controllers/saches_controller.rb
class SachesController < ApplicationController
  before_action :set_sach, only: %i[ show edit update destroy ]

  # GET /saches or /saches.json
  def index
    @saches = Sach.all
  end

  # GET /saches/1 or /saches/1.json
  def show
  end

  # GET /saches/new
  def new
    @sach = Sach.new
  end

  # GET /saches/1/edit
  def edit
  end

  # POST /saches or /saches.json
  def create
    @sach = Sach.new(sach_params)

    respond_to do |format|
      if @sach.save
        format.html { redirect_to sach_url(@sach), notice: "Sach was successfully created." }
        format.json { render :show, status: :created, location: @sach }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saches/1 or /saches/1.json
  def update
    respond_to do |format|
      if @sach.update(sach_params)
        format.html { redirect_to sach_url(@sach), notice: "Sach was successfully updated." }
        format.json { render :show, status: :ok, location: @sach }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saches/1 or /saches/1.json
  def destroy
    @sach.destroy

    respond_to do |format|
      format.html { redirect_to saches_url, notice: "Sach was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sach
      @sach = Sach.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sach_params
      params.require(:sach).permit(:stt, :ma_hs, :ho_va_ten, :lop, :ma_sach, :ten_sach, :ten_tac_gia, :tu_sach, :so_bm, :ngay_muon, :ngay_tra, :so_ngay, :ghi_chu)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles1_helper.rb
module Articles1Helper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/saches_helper.rb
module SachesHelper
end

app/views/articles/_header.html.erb
<div class="px-4">
  <div class="d-flex justify-conten-start">
    <h1 class="text-success fs-4 d-flex flex-column align-items-center">
      <span>THƯ VIỆN</span> TRƯỜNG TIỂU HỌC PHONG THẠNH TÂY A
    </h1>
  </div>
  
</div>

app/views/articles/index.html.erb
<h1>hello</h1>

app/views/articles1/index.html.erb
<h1>Articles1#index</h1>
<p>Find me in app/views/articles1/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Blog!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
      <%= render 'articles/header' %>
      <div class="container">
        <br>
        <%= yield %>
      </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/saches/_form.html.erb
<%= form_with(model: sach) do |form| %>
  <% if sach.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sach.errors.count, "error") %> prohibited this sach from being saved:</h2>

      <ul>
        <% sach.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :stt, style: "display: block" %>
    <%= form.number_field :stt %>
  </div>

  <div>
    <%= form.label :ma_hs, style: "display: block" %>
    <%= form.text_field :ma_hs %>
  </div>

  <div>
    <%= form.label :ho_va_ten, style: "display: block" %>
    <%= form.text_field :ho_va_ten %>
  </div>

  <div>
    <%= form.label :lop, style: "display: block" %>
    <%= form.text_field :lop %>
  </div>

  <div>
    <%= form.label :ma_sach, style: "display: block" %>
    <%= form.text_field :ma_sach %>
  </div>

  <div>
    <%= form.label :ten_sach, style: "display: block" %>
    <%= form.text_field :ten_sach %>
  </div>

  <div>
    <%= form.label :ten_tac_gia, style: "display: block" %>
    <%= form.text_field :ten_tac_gia %>
  </div>

  <div>
    <%= form.label :tu_sach, style: "display: block" %>
    <%= form.text_field :tu_sach %>
  </div>

  <div>
    <%= form.label :so_bm, style: "display: block" %>
    <%= form.text_field :so_bm %>
  </div>

  <div>
    <%= form.label :ngay_muon, style: "display: block" %>
    <%= form.date_field :ngay_muon %>
  </div>

  <div>
    <%= form.label :ngay_tra, style: "display: block" %>
    <%= form.date_field :ngay_tra %>
  </div>

  <div>
    <%= form.label :so_ngay, style: "display: block" %>
    <%= form.number_field :so_ngay %>
  </div>

  <div>
    <%= form.label :ghi_chu, style: "display: block" %>
    <%= form.text_field :ghi_chu %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/saches/_sach.html.erb
<div id="<%= dom_id sach %>">
  <p>
    <strong>Stt:</strong>
    <%= sach.stt %>
  </p>

  <p>
    <strong>Ma hs:</strong>
    <%= sach.ma_hs %>
  </p>

  <p>
    <strong>Ho va ten:</strong>
    <%= sach.ho_va_ten %>
  </p>

  <p>
    <strong>Lop:</strong>
    <%= sach.lop %>
  </p>

  <p>
    <strong>Ma sach:</strong>
    <%= sach.ma_sach %>
  </p>

  <p>
    <strong>Ten sach:</strong>
    <%= sach.ten_sach %>
  </p>

  <p>
    <strong>Ten tac gia:</strong>
    <%= sach.ten_tac_gia %>
  </p>

  <p>
    <strong>Tu sach:</strong>
    <%= sach.tu_sach %>
  </p>

  <p>
    <strong>So bm:</strong>
    <%= sach.so_bm %>
  </p>

  <p>
    <strong>Ngay muon:</strong>
    <%= sach.ngay_muon %>
  </p>

  <p>
    <strong>Ngay tra:</strong>
    <%= sach.ngay_tra %>
  </p>

  <p>
    <strong>So ngay:</strong>
    <%= sach.so_ngay %>
  </p>

  <p>
    <strong>Ghi chu:</strong>
    <%= sach.ghi_chu %>
  </p>

</div>

app/views/saches/edit.html.erb
<h1>Editing sach</h1>

<%= render "form", sach: @sach %>

<br>

<div>
  <%= link_to "Xem sách", @sach %> |
  <%= link_to "Quay lại", saches_path %>
</div>

app/views/saches/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="d-flex align-items-center justify-content-between">
    <h2 class="text-warning text-center">QUẢN LÝ CHO HỌC SINH MƯỢN SÁCH</h2>
    <div class="d-flex align-items-center">
      <p class="text-primary">Quy định ngày quá hạn</p>
      <p class="ms-2 p-3 border border-success">3</p>
    </div>
  </div>
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>STT</th>
        <th>Mã HS</th>
        <th>Họ và tên</th>
        <th>Lớp</th>
        <th>Mã sách</th>
        <th>Tên sách</th>
        <th>Tên tác giả</th>
        <th>Tủ sách</th>
        <th>Số BM</th>
        <th>Ngày mượn</th>
        <th>Ngày trả</th>
        <th>Số ngày</th>
        <th>Ghi chú</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @saches.each do |sach271| %>
        <tr>
          <td><%= sach271.stt %></td>
          <td><%= sach271.ma_hs %></td>
          <td><%= sach271.ho_va_ten %></td>
          <td><%= sach271.lop %></td>
          <td><%= sach271.ma_sach %></td>
          <td><%= sach271.ten_sach %></td>
          <td><%= sach271.ten_tac_gia %></td>
          <td><%= sach271.tu_sach %></td>
          <td><%= sach271.so_bm %></td>
          <td><%= sach271.ngay_muon %></td>
          <td><%= sach271.ngay_tra %></td>
          <td><%= sach271.so_ngay %></td>
          <td><%= sach271.ghi_chu %></td>
          <td><%= link_to 'Xem', sach271 %> <br>
          <%= link_to 'Sửa', edit_sach_path(sach271) %>
          <br>
          <%= link_to 'Xóa', sach271, :confirm => 'Are you sure?',
            :method => :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>


<%= link_to "Thêm sách", new_sach_path %>

app/views/saches/new.html.erb
<h1>New sach</h1>

<%= render "form", sach: @sach %>

<br>

<div>
  <%= link_to "Quay lại", saches_path %>
</div>

app/views/saches/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sach %>

<div>
  <%= link_to "Sửa sách", edit_sach_path(@sach) %> |
  <%= link_to "Quay lại", saches_path %>

  <%= button_to "Xóa sách", @sach, method: :delete %>
</div>